### PR TITLE
lcm hcf calculator added

### PR DESCRIPTION
**Pull request by jugeshraghav**
### Description

(Describe your project over here.)

### Checklist

- [x] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [x] I've added my Project's name and description to `Index.md`
- [x] I've made a README.md file for my Project.
- [x] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number
#346

### CODE REVIEW

**Comment by jugeshraghav** [comment]
hey @harshita2216  please look at it

**Review by harshita2216 — CHANGES_REQUESTED** [review]
https://www.codefactor.io/repository/github/ayushparikh-code/web-dev-mini-projects/pull/364

Kindly make the following changes.

**Comment by jugeshraghav** [comment]
There is only one error and that is something that I don't think so could
be resolved. I don't know what to change in it.

**Comment by jugeshraghav** [comment]
It would be great if you could tell me what to do

**Comment by jugeshraghav** [comment]
@harshita please have a look

**Review by harshita2216 — APPROVED** [review]

**Pull request merged**
