### PR TITLE
Created index.md 

### PR DESCRIPTION
**Pull request by Atif0604**
Hey @chicken-biryani 
This PR will Resolve => Create index.md #91
Please Review my PR

### CODE REVIEW

**Comment by chicken-biryani** [comment]
@Atif0604 can you put it in a table form... Using markdown instead of Html? 

This would help people to put their project in as well.

**Comment by Atif0604** [comment]
> @Atif0604 can you put it in a table form... Using markdown instead of Html?
> 
> This would help people to put their project in as well.
> 
> You can use https://www.github.com/chicken-biryani/GitPracticeSessionBeginners/tree/main/Batch'23%2FMembers.md for reference.
> 
> Please?

Ohk I'll rewrite in markdown @chicken-biryani

**Comment by chicken-biryani** [comment]
Thankyou, @Atif0604 ! This was need for a long time! :)

Does it consist of all the projects? If you want we can pause merging for 3 hours and you can add all the other projects in a new PR!

**Comment by Atif0604** [comment]
> Thankyou, @Atif0604 ! This was need for a long time! :)

It's My Pleasure @chicken-biryani 😊

**Comment by Atif0604** [comment]
Hey @Ayushparikh-code @chicken-biryani @harshita2216 
Please Add LGMSOC21 label to this PR that it should be showing in the label section of PR as my PR is not being counted just because the LGMSOC21 label is not showed up in label section

**Pull request merged**
