### PR TITLE
Adding the photo--editor folder in the repo

### PR DESCRIPTION
**Pull request by soma2000-lang**
### Description
photo --editor is a Photo editor where one can flip(both horizontally and vertically),resize ,gray scale images

### Checklist

- [ ] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [ ] I've made a README.md file for my Project.
- [ ] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

#230

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@chicken-biryani  Please look into this pr

**Review by harshita2216 — CHANGES_REQUESTED** [review]
Your readme file should have the following details -
1. Introduction
2. Use of the project
3. Steps to use it locally
4. Screenshots (your screenshots doesn't seem to work)

Also, please add your project details to index.md file.

**Review by harshita2216 — COMMENTED** [review]
5. Tech stack also! @soma2000-lang

**Comment by harshita2216** [comment]
> Your readme file should have the following details -
> 
> 1. Introduction
> 2. Use of the project
> 3. Steps to use it locally
> 4. Screenshots (your screenshots doesn't seem to work)
> 
> Also, please add your project details to index.md file.

I've asked you to add your project details to index.md file as well. Please do that! Thanks.

**Review by harshita2216 — APPROVED** [review]

**Comment by soma2000-lang** [comment]
@harshita2216 @chicken-biryani  I have made the fequired changes
Can u plz merge now

**Comment by harshita2216** [comment]
> @harshita2216 @chicken-biryani  I have made the required changes
> Can u plz merge now

I will merge it tomorrow after I resolve the conflicts. Don't worry!

**Comment by soma2000-lang** [comment]
Okay thanks

**Comment by harshita2216** [comment]
> Okay thanks

It is difficult to resolve conflicts on the phone, hence I have only approved it for now. 
It will be merged tomorrow morning positively. :)

**Pull request merged**
