### PR TITLE
Basic Contact Form

### PR DESCRIPTION
**Pull request by sonamgupta136**
Merge #185 to main branch

### CODE REVIEW

**Comment by sonamgupta136** [comment]
@harshita2216 #185 please merge

**Comment by chicken-biryani** [comment]
@sonamgupta136 This PR doesn't make sense. Why don't you add a new project? And do these changes in that?

**Review by harshita2216 — CHANGES_REQUESTED** [review]
Hey, you haven't added the entire project folder?

**Comment by chicken-biryani** [comment]
@sonamgupta136 If you are having difficulties, why don't you text us on discord, we are there to help you out.

[Link to the discord](https://discord.com/channels/852809992729919489/860550126874394634)

**Pull request closed without merging**
