### PR TITLE
Battery Percentage Indicator

### LINKED ISSUE #95: Battery Percentage Indicator
This will show the battery percentage of the system.
Can I work on this issue? I'm a participant of LGM Soc21.

### PR DESCRIPTION
**Pull request by Jagannath8**
This is a battery indicator app which is used to know battery percentage of the system.

Fixes #95

### CODE REVIEW

**Comment by Jagannath8** [comment]
When I updated the index.md file, I only added Battery Percentage Indicator. But it shows that some lines are deleted.
Yesterday also I'm facing the same issue, how to overcome it @chicken-biryani @harshita2216 @Ayushparikh-code 

image
image

**Comment by chicken-biryani** [comment]
Hey, so I don't see any major difference. A lot of people are contributing to index.md at the same time. So when more than one person works on the same file, conflicts occur. I don't think there's anything to worry about, everything looks good to me.

**Comment by chicken-biryani** [comment]
Hey, so I don't see any major difference. A lot of people are contributing to index.md at the same time. So when more than one person works on the same file, conflicts occur. I don't think there's anything to worry about, everything looks good to me.

**Comment by chicken-biryani** [comment]
Can you try and re edit them the way they originally were?

**Comment by Jagannath8** [comment]
> Can you try and re edit them the way they originally were?

Yes, I've updated @chicken-biryani

**Comment by Ayushparikh-code** [comment]
> When I updated the index.md file, I only added Battery Percentage Indicator. But it shows that some lines are deleted.
> Yesterday also I'm facing the same issue, how to overcome it @chicken-biryani @harshita2216 @Ayushparikh-code
> 
> image
> image

don't worry always fetch the latest upstream of original repo and merge it to ur cloned repo , then start add ur project to index.md and create pull request,  do not worry about it !

**Comment by Ayushparikh-code** [comment]
> > When I updated the index.md file, I only added Battery Percentage Indicator. But it shows that some lines are deleted.
> > Yesterday also I'm facing the same issue, how to overcome it @chicken-biryani @harshita2216 @Ayushparikh-code
> > image
> > image
> 
> don't worry @Jagannath8  always fetch the latest upstream of original repo and merge it to ur cloned repo , then start add ur project to index.md and create pull request, do not worry about it !

**Pull request merged**
