### PR TITLE
Added Project : Compound Interest Calculator

### LINKED ISSUE #89: SIP Compound Interest Calculator
I would like to add this mini-project named: SIP Compound Interest Calculator.
It is made by HTML, CSS & JS.

Please assign me so that I can work on this issue @chicken-biryani @Ayushparikh-code

### PR DESCRIPTION
**Pull request by mrkc2303**
This PR fixes #89 

I have added a project: Compound Interest Calculator using: HTML, CSS, Bootstrap, and JS.

Please Review my PR.

Thank You

### CODE REVIEW

**Review by Ayushparikh-code — CHANGES_REQUESTED** [review]
add your project name and description in index.md file of this repo

**Comment by mrkc2303** [comment]
I have already added Project Name and Description in Readme.md file. Do you want me to add the same in index.html??
@Ayushparikh-code

**Comment by Ayushparikh-code** [comment]
> I have already added Project Name and Description in Readme.md file. Do you want me to add the same in index.html??
> @Ayushparikh-code

yeah I know u added it in ur project readme file but I want u too add ur project in this file too - https://github.com/Ayushparikh-code/Web-dev-mini-projects/blob/main/Index.md

**Comment by mrkc2303** [comment]
Done
Please Check!! @Ayushparikh-code

**Comment by mrkc2303** [comment]
@Ayushparikh-code 
Conflict in the files has been resolved. Please Check!!

THANK YOU!

**Review by Ayushparikh-code — APPROVED** [review]

**Comment by mrkc2303** [comment]
Hi,
Kindly add a level to my PR. I think you forgot it.
@Ayushparikh-code 

Thank You!

**Comment by mrkc2303** [comment]
Hi,
Kindly add a level to my PR. I think you forgot it.
@Ayushparikh-code 

Thank You!

**Pull request merged**
