### PR TITLE
Improved DIGITAL-JAVASCRIPT-CLOCK 's README 

### PR DESCRIPTION
**Pull request by Atif0604**
Hey @chicken-biryani 
This PR will Resolve => Improve DIGITAL-JAVASCRIPT-CLOCK 's README #65
Please Review my PR

### CODE REVIEW

**Comment by Atif0604** [comment]
hey @chicken-biryani 
why there is conflict all of a sudden when made a PR it wasn't there 🥺😢

**Comment by chicken-biryani** [comment]
@Atif0604 conflicts usually occur when more than one person is working in the same file.

**Comment by Atif0604** [comment]
> @Atif0604 conflicts usually occur when more than one person is working in the same file.

What Should I Do Now 😢

**Comment by chicken-biryani** [comment]
As you can see @Atif0604, @RiyaGupta89 and you were working on the same files! Thus a conflict occurred.

**Comment by Atif0604** [comment]
> As you can see @Atif0604, @RiyaGupta89 and you were working on the same files! Thus a conflict occurred.

Ohh! Thank You So much
Also @chicken-biryani you forgot to add LGMSOC label to the PR

**Pull request merged**
