### PR TITLE
Adding News App Project

### PR DESCRIPTION
**Pull request by RiyaGupta89**
# News App

### CODE REVIEW

**Comment by RiyaGupta89** [comment]
@harshita2216 I've made the PR here please review.

**Comment by harshita2216** [comment]
@RiyaGupta89 there are no new changes. Please check!

**Comment by RiyaGupta89** [comment]
@harshita2216 Mam actually the thing is that my code was ready yesterday itself, I've successfully added the project yesterday only but I did it on the main branch. And just before that I've made a PR for correcting the readme file that too on the main branch. Therefore I should have pushed the code at that point of time only but I thought that this would be a wrong impression that I am pushing the code of resolving more than one issue altogether so I thought as soon as I will get my previous PR merged, I will push this code too. I was waiting from the morning but my PR got merged at the night yesterday although my code was already committed and all set to push but I was waiting for my previous PR. Otherwise my news app and that readme code commits, all of those would have been together. It is the case why the conflict occurred. Please tell me how I can resolve this and how not to repeat this mistake again.

**Comment by harshita2216** [comment]
Hey don't worry. If you have multiple issues, it is expected you do it under different pull requests. 
Conflicts happen when two or more people write some code on the same file of any file. So GitHub doesn't understand which ones to keep and which ones to omit. In such a case, it shows conflicts which we ourselves have to resolve. 
Hence, I have taken the responsibility to resolve the conflicts as there are many people making PRs and they may not know which ones to keep. So if there's any merge conflicts, you need not worry about them. 
Take your time to finish all your pending issues. We are in no hurry.  :)
@RiyaGupta89

**Comment by harshita2216** [comment]
Please link the PR you are talking about? 
Because I cannot see the project merged.

**Comment by RiyaGupta89** [comment]
@harshita2216 You see all of these 19 commits above, I pushed them when I made a PR today morning. Idk why it is not present in the pull request list. Is it not possible that the PR got merged? Please check if the current repo has news-app folder or not.

**Comment by harshita2216** [comment]
Yeah that is why I merged this one to check but it isn't in the main repo. 
Do one thing, just copy and paste the same thing and make a PR again from a different branch. 
By that time, I'll check what's going wrong with this one.
@RiyaGupta89

**Review by harshita2216 — COMMENTED** [review]
The problem is here. In trying to resolve conflicts, you've deleted all the files. 
In the "trying to resolve conflicts" commit.

**Comment by RiyaGupta89** [comment]
@harshita2216 Oh, should I add the news-app folder again?

**Comment by RiyaGupta89** [comment]
@harshita2216  I have made the new PR and where I have added the project folder back and also added the project name in the index.md.

**Pull request merged**
