### PR TITLE
personal blog template added.

### PR DESCRIPTION
**Pull request by jugeshraghav**
### Description

(Describe your project over here.)

### Checklist

- [x] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [x] I've added my Project's name and description to `Index.md`
- [x] I've made a README.md file for my Project.
- [x] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number
#285

### CODE REVIEW

**Comment by jugeshraghav** [comment]
hey ! Please have a look @harshita2216

**Review by harshita2216 — CHANGES_REQUESTED** [review]
https://www.codefactor.io/repository/github/ayushparikh-code/web-dev-mini-projects/pull/288

Kindly make the following changes.

**Comment by jugeshraghav** [comment]
Will you tell me what is this code factor. I am curious

**Comment by jugeshraghav** [comment]
i changed all the code as mentioned in the issues but still the changes are not reflected. @harshita2216

**Comment by jugeshraghav** [comment]
I am closing this PR as one more PR is created by mistake .

**Pull request closed without merging**
