### PR TITLE
added Live clock

### PR DESCRIPTION
**Pull request by palaksinghania05**
### Description

Added Live Clock using React Native Project.
Modified Readme of Weight Converter

### Checklist

- [✔] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [✔] I've added my Project's name and description to `Index.md`
- [✔] I've made a README.md file for my Project.
- [✔] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

#150

### CODE REVIEW

**Review by harshita2216 — CHANGES_REQUESTED** [review]
You have just changed your readme file. Clock website hasn't been pushed. Please check.

**Comment by palaksinghania05** [comment]
Okay. I will check again.

**Comment by palaksinghania05** [comment]
Updated. Please check again.

**Review by harshita2216 — APPROVED** [review]

**Comment by harshita2216** [comment]
@palaksinghania05, I've deleted both files, yet I am unable to merge the PR. Kindly make a new pull request WITHOUT any changes to the index.md and Weight Converter's readme file, as I have already updated those.

**Pull request closed without merging**
