### PR TITLE
index-corrected

### PR DESCRIPTION
**Pull request by nisha331**
### Description

index corrected

### Checklist

- [x] I've been assigned an issue related to this PR.

## Related Issues or Pull Requests number
issue #306 
(Write your answer here.)

### CODE REVIEW

**Review by harshita2216 — COMMENTED** [review]
Should we have these projects listed in alphabetical order, @nisha331?

**Comment by nisha331** [comment]
Ahh Yes @harshita2216 we can have it.  Is there any other  way then doing it manually?

**Comment by harshita2216** [comment]
We'll keep this open till the end of the program. You can keep updating the index.md as and when required, so kindly please keep checking. :)

**Comment by nisha331** [comment]
Hey @harshita2216 is is possible that u merge the edit done till the moment . As I have to repeat the same thing for a set of lines in order to remove the conflict. I will make sure that all goes well after the merge of the present code.

**Comment by harshita2216** [comment]
You can make the changes here itself. Everytime someone's project gets merged, it's your task to update and push it here in alphabetical order.

**Comment by harshita2216** [comment]
Please keep updating this. We'll be giving the level based on how much you've worked on this issue. (It would be greater than equal to level 2) 
Also, please add the missing projects as well.

**Comment by harshita2216** [comment]
Try to update this PR on a daily basis as 2-3 PRs get merged everyday.

**Comment by harshita2216** [comment]
Hey, kindly make changes asap as this will be merged very soon. 
I see a few mistakes in the alphabetical order, kindly check that as well. (We check the 2nd letter if 1st letter is same.)

**Comment by nisha331** [comment]
@harshita2216 is it fine ?

**Review by harshita2216 — CHANGES_REQUESTED** [review]
Some new and old projects are missing. Kindly check please.

**Review by harshita2216 — COMMENTED** [review]
Inactive.

**Pull request closed without merging**
