### PR TITLE
Added Weather App

### PR DESCRIPTION
**Pull request by Atif0604**
Hey @Ayushparikh-code 
This PR will Resolve Add Weather App #24
Please Review my PR

### CODE REVIEW

**Comment by chicken-biryani** [comment]
Hey, @Atif0604 looks good to me. Can you add a small README.md file to your project... 

Contents of the README:

- Project overview.
- Use of the project.
- Stack of your project.
- How to set up / run your project.
- Screenshots of the pages / output.
A short description under each screenshot... Describing the page a little bit

This may seem like a tedious task for now.... But it will be helpful to visitors who view your project.

**Comment by Atif0604** [comment]
> Hey, @Atif0604 looks good to me. Can you add a small README.md file to your project...
> 
> Contents of the README:
> 
> * Project overview.
> * Use of the project.
> * Stack of your project.
> * How to set up / run your project.
> * Screenshots of the pages / output.
>   A short description under each screenshot... Describing the page a little bit
> 
> This may seem like a tedious task for now.... But it will be helpful to visitors who view your project.

can i do this in another PR ? @chicken-biryani

**Comment by Atif0604** [comment]
> Hey, @Atif0604 looks good to me. Can you add a small README.md file to your project...
> 
> Contents of the README:
> 
> * Project overview.
> * Use of the project.
> * Stack of your project.
> * How to set up / run your project.
> * Screenshots of the pages / output.
>   A short description under each screenshot... Describing the page a little bit
> 
> This may seem like a tedious task for now.... But it will be helpful to visitors who view your project.

sure

**Comment by chicken-biryani** [comment]
So we could do two things.

1) You do the changes, and commit.
2) I close this PR, and you create a completely new PR.

Let everything related to one project be under one PR.

Don't worry about the points for LGM - SOC.

**Comment by Atif0604** [comment]
> So we could do two things.
> 
> 1. You do the changes, and commit within this PR itself ( Which would be preferable).
> 2. I close this PR, and you create a completely new PR.
> 
> Let everything related to one project be under one PR.
> 
> Don't worry about the points for LGM - SOC.
> 
> @Atif0604

Ok i'll do in this PR Only

**Review by Ayushparikh-code — APPROVED** [review]
looks nice

**Comment by Atif0604** [comment]
> looks nice

Hey @Ayushparikh-code 
can you remove the video as file as it isn't working
I thought of making it more creative but it didn't work

**Comment by Ayushparikh-code** [comment]
> > looks nice
> 
> Hey @Ayushparikh-code
> can you remove the video file as it isn't working
> I thought of making Readme more creative but it didn't work

yeah I deleted that file succesfully

**Comment by Atif0604** [comment]
> > > looks nice
> > 
> > 
> > Hey @Ayushparikh-code
> > can you remove the video file as it isn't working
> > I thought of making Readme more creative but it didn't work
> 
> yeah I deleted that file succesfully

Thank You So much @Ayushparikh-code

**Comment by Atif0604** [comment]
Hey @Ayushparikh-code @chicken-biryani @harshita2216 
Please Add LGMSOC21 label to this PR that it should be showing in the label section of PR as my PR is not being counted just because the LGMSOC21 label is not showed up in label section

**Pull request merged**
