### PR TITLE
Sudoku Solver

### PR DESCRIPTION
**Pull request by soma2000-lang**
### Sudoku Solver 

(Made using html,javascript and css using he concept of backtracking

### Checklist

- [x] I've been assigned an issue related to this PR.
- [x] I've used beautifiers.
- [x] I've added my Project's name and description to `Index.md`
- [x] I've made a README.md file for my Project.
- [x] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

(#270)

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@harshita2216  can you please check why the checks have failed??
I cannot understand

**Comment by harshita2216** [comment]
These are the issues. 
And dont worry about the merge conflicts. I will resolve them.

**Comment by soma2000-lang** [comment]
@harshita2216  ok I am removing them

**Comment by soma2000-lang** [comment]
@harshita2216  checks have passed

**Review by harshita2216 — APPROVED** [review]

**Comment by soma2000-lang** [comment]
@harshita2216  kindly merge

**Comment by harshita2216** [comment]
> @harshita2216  kindly merge

I've already approved it hence it will be merged. Please don't worry.

**Pull request merged**
