### PR TITLE
Added Notes website in the repository

### LINKED ISSUE #50: Website that keeps your notes
Can I add a website in which you can add your notes and also search them?

### PR DESCRIPTION
**Pull request by RiyaGupta89**
# Resolves #50 
Added the notes keeping website in the project which stores the notes of the user in the local storage. A user is allowed to delete that note anytime they want.

### CODE REVIEW

**Review by Ayushparikh-code — CHANGES_REQUESTED** [review]
can u make its readme better by adding some screenshots/images !

**Comment by RiyaGupta89** [comment]
@Ayushparikh-code Sure, I will.

**Comment by RiyaGupta89** [comment]
@Ayushparikh-code Done. Please have a look.

**Review by Ayushparikh-code — APPROVED** [review]
LGTM

**Pull request merged**
