### PR TITLE
2048game

### PR DESCRIPTION
**Pull request by Gyynnn**
### Description

(2048 Game on a website.)

### Checklist

- [x] I've been assigned an issue related to this PR.
- [x] I've used beautifiers.
- [x] I've added my Project's name and description to `Index.md`
- [x] I've made a README.md file for my Project.
- [x] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

#317

### CODE REVIEW

**Comment by harshita2216** [comment]
Kindly do not make PRs before creating the issues.

**Comment by Gyynnn** [comment]
oops sorry im using github for the first time and not familiar with it yet

**Comment by harshita2216** [comment]
Yeah, create it and then reopen this. I'll review it then!

**Review by harshita2216 — APPROVED** [review]

**Comment by harshita2216** [comment]
Great work! Will merge this tomorrow morning after resolving the conflicts on my pc. :)

**Comment by harshita2216** [comment]
Also, are you a LGMSOC participant or you are contributing in general?

**Comment by Gyynnn** [comment]
Thanks! I am not a LGMSOC participant, just doing this for my own school project to learn about how Github works.

**Pull request merged**
