### PR TITLE
survey form added.

### PR DESCRIPTION
**Pull request by jugeshraghav**
### Description

(Describe your project over here.)

### Checklist

- [x] I've been assigned an issue related to this PR.
- [ ] I've used beautifiers.
- [x] I've added my Project's name and description to `Index.md`
- [x] I've made a README.md file for my Project.
- [x] The README.md file of my projrct contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots). 

## Related Issues or Pull Requests number

#331

### CODE REVIEW

**Comment by jugeshraghav** [comment]
hey @harshita2216 please have a look.

**Comment by jugeshraghav** [comment]
I have resolved the conflicts @harshita2216

**Comment by jugeshraghav** [comment]
I have resolved the conflicts @harshita2216

**Comment by harshita2216** [comment]
@jugeshraghav, thanks for doing that. 
Actually my laptop isn't working and I'm expecting the technician in 4-5 days. Hence, I was unable to do it. 
Thank you so much!

**Pull request merged**
