### PR TITLE
Temperature Convertor added

### PR DESCRIPTION
**Pull request by joshi-kaushal**
### Description

Created a new project *Temperature Convertor*

### Checklist

- [x] I've been assigned an issue related to this PR.
- [x] I've used beautifiers.
- [x] I've added my Project's name and description to `Index.md`
- [x] I've made a README.md file for my Project.
- [x] The README.md file of my Project contains Project title, Description, Use of project, Set up, Stack used and Output (Screenshots).

### CODE REVIEW

**Review by harshita2216 — CHANGES_REQUESTED** [review]
Everything looks good, just add your project details to index.md file.

**Comment by harshita2216** [comment]
@joshi-kaushal please don't copy paste the entire thing. Just add your details only please.

**Comment by harshita2216** [comment]
https://github.com/Ayushparikh-code/Web-dev-mini-projects/blob/493f6ca96c4d4e97646a097edf59fa52ee7b64c2/Index.md

Also this is how it looks after your changes. @joshi-kaushal

**Comment by joshi-kaushal** [comment]
@harshita2216 I pasted link from my forked repo since PR is not accepted yet, check the link first, I'll resolve the conflict if the link is okay.

**Comment by harshita2216** [comment]
Put tree/main @joshi-kaushal

**Comment by harshita2216** [comment]
And the link should have Ayush's repo.

**Comment by harshita2216** [comment]
@joshi-kaushal, I have made the changes to the file for you. Make sure you understand what I have done and try to do it yourself the next time. 💯

**Comment by joshi-kaushal** [comment]
Thank you so much! I really appreciate this :)

**Pull request merged**
